theme: jekyll-theme-cayman
title: Open Actuarial Textbooks
description: This project provides interactive, online, freely available texts. Our first effort, Loss Data Analytics, provides core training on one of the foundations of actuarial science, loss data modeling. 
